heartFund/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/',views.register_view, name="register"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout")
]

heartFund/apps/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('',views.index,name='index')
]

heartFund/apps/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    # API endpoints
    path("api/", views.project_list_create_api, name="project_list_create_api"),
    path("api/<int:pk>/", views.project_detail_api, name="project_detail_api"),
    path("api/<int:pk>/contributions/", views.project_contributions_api, name="project_contributions_api"),
    path("api/mine/", views.user_projects_api, name="user_projects_api"),
    path("api/search/", views.search_projects_api, name="search_projects_api"),

    # Frontend pages
    path("add/", views.add_project_page, name="add_project"),
    path("mine/", views.my_projects, name="my_projects"),
]


# GET /projects/api/ → all projects # type: ignore
# POST /projects/api/ → create project (must be logged in)
# GET /projects/api/<id>/ → view single project
# PUT /projects/api/<id>/ → update project (only if owner)
# DELETE /projects/api/<id>/ → delete project (only if owner)
# GET /projects/api/mine/ → list projects owned by logged-in user
# GET /projects/api/search/?start=2025-09-01&end=2025-09-30 → search projects by date range

heartFund/heartfund/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("apps.accounts.urls")),
    path('', include('apps.home.urls')),
    path("projects/", include("apps.projects.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heartFund/templates/partials/footer.html
<footer class="footer">
  <div class="footer-container">
    <div class="footer-about">
      <h2>HeartFund</h2>
      <p>Transforming Ideas into Reality.</p>
    </div>

    <div class="footer-links">
      <h3>Quick Links</h3>
      <ul>
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="#content">Campaigns</a></li>
        <li><a href="{% url 'projects:add_project' %}">Start a Campaign</a></li>
      </ul>
    </div>
  </div>

  <div class="footer-bottom">
  </div>
</footer>

heartFund/templates/partials/navbar.html
<header>
  <nav>
    <!--Sidebar -->
    <ul class="sidebar">
      <li onclick="hideSidebar()">
        <a href="#">
          <svg xmlns="http://www.w3.org/2000/svg" height="26px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
            <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/>
          </svg>
        </a>
      </li>
      <li><a href="{% url 'home:index' %}">Home</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'projects:my_projects' %}">My Campaigns</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
      {% endif %}
    </ul>

    <!-- Navbar -->
    <ul>
      <li>
        <a href="{% url 'home:index' %}" class="logo">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            height="28px"
            viewBox="0 -960 960 960"
            width="28px"
            fill="#d8a457"
          ><path d="M40-120v-160q0-34 23.5-57t56.5-23h131q20 0 38 10t29 27q29 39 71.5 61t90.5 22q49 0 91.5-22t70.5-61q13-17 30.5-27t36.5-10h131q34 0 57 23t23 57v160H640v-91q-35 25-75.5 38T480-160q-43 0-84-13.5T320-212v92H40Zm120-280q-50 0-85-35t-35-85q0-51 35-85.5t85-34.5q51 0 85.5 34.5T280-520q0 50-34.5 85T160-400Zm640 0q-50 0-85-35t-35-85q0-51 35-85.5t85-34.5q51 0 85.5 34.5T920-520q0 50-34.5 85T800-400Zm-320-80q-68-62-111-104.5T302-658q-24-31-33-54.5t-9-47.5q0-50 35-85t86-35q28 0 54 12.5t45 33.5q19-21 45-33.5t54-12.5q51 0 86 35t35 85q0 24-9 47.5T658-658q-24 31-67 73.5T480-480Zm0-108q72-66 106-107.5t34-64.5q0-17-12-28.5T579-800q-12 0-23.5 7T532-772l-51 59-51-57q-14-16-25.5-23t-23.5-7q-17 0-29 11.5T340-760q0 23 34 64.5T480-588Zm0 0Z"/></svg>
          <span>HeartFund</span>
        </a>
      </li>
      <li class="hideOnMobile"><a href="{% url 'home:index' %}">Home</a></li>
      {% if user.is_authenticated %}
        <li class="hideOnMobile"><a href="{% url 'projects:my_projects' %}">My Campaigns</a></li>
        <li class="hideOnMobile"><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
        <li class="hideOnMobile"><a href="{% url 'accounts:login' %}">Login</a></li>
      {% endif %}
      <li class="menu-button" onclick="showSidebar()">
        <a href="#">
          <svg xmlns="http://www.w3.org/2000/svg" height="26px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
            <path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/>
          </svg>
        </a>
      </li>
    </ul>
  </nav>
</header>

<script>
  function showSidebar() {
    document.querySelector(".sidebar").style.display = "flex";
  }
  function hideSidebar() {
    document.querySelector(".sidebar").style.display = "none";
  }
</script>